npmPublishAccess: "public"
npmScopes:
  lberrocal:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN}
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
